language: php
git:
  submodules: false

services:
  - docker

before_install:
  - docker pull composer
  - docker pull php
  - docker run -v `pwd`:/app composer /bin/sh -c "php composer.phar install"
  - npm install --global prettier

script:
  - docker run -v `pwd`:/app -w /app php /bin/sh -c "./phpcs.sh"
  - prettier -l '**/*.js' '**/*.ts' '**/*.tsx'
