version: "3.2"
services:
  api:
    build: ../api
    image: coursetable/api
    restart: always
    ports:
      - "8039:8039"
      - "8038:8080"
    expose:
      - 8039
    volumes:
      - ../api:/app
      - ./wait-for-it.sh:/app/wait-for-it.sh
    user: "1000"
    depends_on:
      - graphql-engine
    environment:
      CANNY_KEY: ${CANNY_KEY?canny_key}
      CHALLENGE_PASSWORD: ${CHALLENGE_PASSWORD?challenge_password}
      FACEBOOK_API_ENDPOINT: ${FACEBOOK_API_ENDPOINT?facebook_api_endpoint}
      FERRY_SECRET: ${FERRY_RELOAD_SECRET?ferry_reload_secret}
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT?frontend_endpoint}
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql
      MYSQL_HOST: ${MYSQL_HOST?host}
      MYSQL_PORT: ${MYSQL_PORT?port}
      MYSQL_USER: ${MYSQL_USERNAME?username}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
      MYSQL_URL: ${MYSQL_URL?mysql_url}
      NODE_ENV: production
      POSTHOG_API_KEY: ${POSTHOG_API_KEY?posthog_api_key}
      POSTHOG_HOST: ${POSTHOG_HOST?posthog_host}
      SESSION_SECRET: ${SESSION_SECRET?session_secret}
      STUDENTS_DB: yaleplus
      YALIES_API_KEY: ${YALIES_API_KEY?yalies_api_key}
      SECURE_PORT: ${SECURE_PORT?secure_port}
      INSECURE_PORT: ${INSECURE_PORT?insecure_port}
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable.rule: Host(`api.coursetable.com`)
      traefik.http.routers.coursetable.tls: true
      traefik.http.routers.coursetable.tls.certResolver: ctresolver
      traefik.http.routers.coursetable.middlewares: gzip-compress@file
    networks:
      - traefik
      - mysql_default
      - default

  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    restart: always
    ports:
      - "8085:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${FERRY_POSTGRES_URI?ferry_db}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - ferry_default
      - default

  legacy:
    image: nginx
    restart: always
    ports:
      - "8075:80"
    volumes:
      - ../legacy:/usr/share/nginx/html:ro
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable-legacy.rule: Host(`legacy.coursetable.com`)
      traefik.http.routers.coursetable-legacy.tls: true
      traefik.http.routers.coursetable-legacy.tls.certResolver: ctresolver
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
  ferry_default:
    external: true
  mysql_default:
    external: true
